### PR TITLE
methods added to cl_xml_document

### PR DESCRIPTION
**Pull request by Ennowulff**
METHODS render_2_string
METHODS create_with_data

### CODE REVIEW

**Review by Ennowulff — COMMENTED** [review]
new line between method-endmethod

**Comment by Ennowulff** [comment]
new try with new pr

**Comment by larshp** [comment]
also feel free to just push more commits to the branch

**Comment by Ennowulff** [comment]
I tried but didn't work. I felt like changing things back and forth and either way there are errors.

**Pull request closed without merging**
