### PR TITLE
Update if_t100_dyn_msg.intf.abap

### PR DESCRIPTION
**Pull request by adventas**
Add missing interfaces.

### CODE REVIEW

**Comment by larshp** [comment]
hi Peter(?), check the findings above, you can fix all manually, or click some times to accept the suggestions

**Comment by adventas** [comment]
Hi Lars, sorry, not Peter, I am Lawrence. Best regards.

**Comment by larshp** [comment]
heh, okay 😄 suggest adding name and affiliation in your github profile, if you like

**Comment by adventas** [comment]
Done.

**Comment by larshp** [comment]
@adventas one more, see above

I just guessed you were from the Hamburg based Adventas?

**Comment by adventas** [comment]
That right.

**Comment by larshp** [comment]
say hi to Peter & Timo 👋

**Comment by adventas** [comment]
Will do.

**Comment by larshp** [comment]
merging, thanks for the fix

**Pull request merged**
