### PR TITLE
Some deps

### PR DESCRIPTION
**Pull request by Zeatynis**
I am not sure if I did it correctly. I spotted later that you don't do these dependencies 1:1 as they are coded in SAP standard. Probably due to licensing issues.

### CODE REVIEW

**Review by Zeatynis — COMMENTED** [review]
Reviewed

**Comment by larshp** [comment]
dont add `.github/workflows/main.yml`

**Comment by larshp** [comment]
if you dont have vscode installed locally, its also possible to use https://github.com/github/dev to run the abaplint extension

**Comment by Zeatynis** [comment]
> dont add `.github/workflows/main.yml`

sorry. Github automatically adds everything I commit now in my repo...

**Comment by larshp** [comment]
thanks 👍

**Pull request merged**
